policies:
  - name: 'sell_low'
    params: [2]
  - name: 'high_low'
    params: [4, 10]
  - name: 'track'
    params: [0, 4]

simulation:
  policy: 'track'
  time_horizon: 40
  discount_factor: 0.99
  initial_price: 16
  initial_bias: 'Up'
  up_step: 1
  down_step: -1
  variance: 2
  iterations: 10000
  print_step: 40

policy_names:
  - 'sell_low'
  - 'high_low'
  - 'track'

state_names:
  - 'price'
  - 'resource'
  - 'bias'

init_state:
  price: 16
  resource: 1
  bias: 'Up'

decision_names:
  - 'sell'
  - 'hold'

exog_params:
  up_step: 1
  down_step: -1
  variance: 2
  bias_df:
    columns: ['Up', 'Neutral', 'Down']
    rows:
      - [0.9, 0.1, 0.0]
      - [0.2, 0.6, 0.2]
      - [0.0, 0.1, 0.9]
